### ISSUE TITLE
UI Draggers changes + collider changes

### ISSUE THREAD

**Issue by Animal42069** [Mantas-2155X/BetterHScenes#1]
Hey Mantas,

Opening this up as a reminder for me to port over the ui draggers changes I made.

I'm also working on another change.  I'm not sure if there is already a mod for this, but basically the goal of the change is to make the penis length appear more static during HScenes rather than growing and shrinking due to a collision point.  What I am doing is adding a new collision point to the HScene and moving it on a frame by frame basis depending on the location of certain objects in the game.  This should make vaginal, anal, and oral sex appear a little bit more realistic.  The zip file contains early results of testing.

[AI-Syoujyo 2020-06-14 05-18-43.zip](https://github.com/Mantas-2155X/BetterHScenes/files/4776241/AI-Syoujyo.2020-06-14.05-18-43.zip)

**Comment by Mantas-2155X** [comment]
Hello again,

I love the idea of making it more static! 
I think there's already two projects trying to accomplish the same, or close goal. I suggest looking into Roy12s PVCollider and what Hooh has been posting in the Illusion Soft discord channels (videos). It shows some very interesting advancements as well. 

Maybe you could try talking to Hooh and working together on the same goal? If he agrees, I think it would be better to move it into a separate plugin due to probably big complexity, but that's up to both of you.

**Comment by Animal42069** [comment]
I've rolled over the UI changes that I made to the AI_BetterHScenes branch into a new fork of this branch.

I'll keep the collider changes out, because they are very much experimental at this point.  I will probably fork off Roy12's PVCollider and move those changes into that fork.  I drew a lot of inspiration from his project, so it is probably a better fit there anyways.  The only thing I'm really worried about is the interaction between one dll moving character locations, and another dll moving a collision location that is based off of character location, which was the main reason I tested it out in this project.

I'll close out this issue and the other one at this point as I'm pretty happy with its current state.  There's definitely some more things that could be added, like your idea of saving offsets to character cards, reducing the bloat of the xml file, and improving the UI (replacing buttons with sliders is one idea).

**Comment by Mantas-2155X** [comment]
Thanks for your great work!
I think we should keep this open until we merge it into the main branch, or if there's any more changes needing to be done.
I've noticed that some code formatting is a little off, it doesn't really matter much but it does stand out

**Comment by Animal42069** [comment]
Sounds good, let me know if anything needs to be done on my end

**Comment by Mantas-2155X** [comment]
- The xml file should be stored somewhere else, not in the game root directory. Maybe the UserData folder? Usually that folder is backed up when updating your game, that way the offsets won't be lost. Also, having a better name for the file would be great.

- After doing some tests, I've noticed that offsets which are fully zero'ed out are still saved and shown in the xml file, some of them are saved as negative zero. It would be good if they were automatically removed if saving zeros.

- Since animations can have many motions like WLoop OLoop etc, the file can get very big. Would it be possible to just append the motion names to one if the numbers are the same? Maybe have a switch (by default) to disable saving of separate motions, since most of the time just changing it for the whole animation is enough.

- I did see some random unused code which can be slightly cleaned up, not a priority but maybe something for the final product

Opening a pull request and discussing the progress there would be slightly more efficient than trying to manage through this issue

I hope this is not too much ^^

**Comment by Animal42069** [comment]
It should be easy enough to move the XML file.

The zero behavior is all happening due to the behavior of the xml serializer class.  I think there are ways to set fields as optional and default that could help.  I'll see what happens.  There;s certainly more efficient ways to store information, but this is the easiest way I know of to store information that contains lists of unknown size.

Originally I was just going to apply offsets to all motions, but on testing I saw that it wasn't always the perfect spot for all motions.  The intended use is to do your first offset save as the "default" save, this will apply the offset to all motions.  Then if you see a motion that needs a separate offset, you would save it off for that motion.  There's probably a way to make that a bit more intuitive in the UI.  But it is easy enough to add a switch to the options to turn that behavior on, while off, all offsets would be saved/read from the "default" motion.

I'll submit a pull request once I get those changes in

**Comment by Mantas-2155X** [comment]
Closed as further discussion has been moved to the [PR](https://github.com/Mantas-2155X/BetterHScenes/pull/2)
